 git clone https://github.com/tpope/vim-surround.git
 git clone https://github.com/rayburgemeestre/phpfolding.vim.git
 git clone https://github.com/scrooloose/syntastic.git
 git clone https://github.com/mattn/emmet-vim.git
 git clone https://github.com/reid/node-jslint.git
 git clone https://github.com/krampstudio/webvim.git
 git clone https://github.com/VundleVim/Vundle.vim.git
 git clone https://github.com/scrooloose/nerdtree.git
 git clone https://github.com/vim-scripts/FuzzyFinder.git
 git clone https://github.com/itchyny/lightline.vim.git
 git clone https://github.com/easymotion/vim-easymotion.git
 git clone https://github.com/tpope/vim-surround.git
 git clone https://github.com/mattn/emmet-vim.git
 git clone https://github.com/Shutnik/jshint2.vim.git
 git clone https://github.com/skammer/vim-css-color.git
 git clone https://github.com/maxbrunsfeld/vim-yankstack.git
 git clone https://github.com/moll/vim-bbye.git
 git clone https://github.com/kien/ctrlp.vim.git
 git clone https://github.com/scrooloose/nerdtree.git
 git clone https://github.com/vim-airline/vim-airline.git
 git clone https://github.com/rking/ag.vim.git
 git clone https://github.com/Slava/vimrc.git
 git clone https://github.com/tpope/vim-pathogen.git
 git clone https://github.com/tpope/vim-fugitive.git
 git clone https://github.com/tpope/vim-sensible.git
